name: build

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: |
          wget https://storage.googleapis.com/remarkable-codex-toolchain/remarkable-platform-image-4.0.117-rm2-public-x86_64-toolchain.sh -O /tmp/toolchain.sh
          sh /tmp/toolchain.sh -y
      - name: Build binary
        run: |
          source /opt/codex/rm2/4.0.117/environment-setup-cortexa7hf-neon-remarkable-linux-gnueabi
          make
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: rmkb-binary
          path: rmkb
      - name: Create release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Version ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Binary hash
        id: binary_hash
        if: steps.create_release.outcome == 'success'
        run: sha256sum rmkb
      - name: Upload release binary
        id: upload_release
        if: steps.binary_hash.outcome == 'success'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rmkb
          asset_name: rmkb
          asset_content_type: application/octet-stream
